exec-once = uwsm app -- dbus-update-activation-environment --systemd --all
exec-once = uwsm app -- systemctl --user import-environment QT_QPA_PLATFORMTHEME

exec-once = uwsm app -- hyprpaper &
exec-once = uwsm app -- hypridle &
exec-once = uwsm app -- /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# brightness control under wayland
exec-once = uwsm app -- wlr-brightness &
exec-once = uwsm app -- nm-applet --indicator &
exec-once = uwsm app -- mako &

exec-once = uwsm app -- gsettings set org.gnome.desktop.interface gtk-theme 'Arc-Dark'
exec-once = uwsm app -- gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'
exec-once = uwsm app -- gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = uwsm app -- gsettings set org.gnome.desktop.interface font-name 'Roboto Mono'

#clipboard
exec-once = uwsm app -- wl-paste --type text --watch cliphist store  #Stores only text data
exec-once = uwsm app -- wl-paste --type image --watch cliphist store #Stores only image data

exec-once = uwsm app -- waybar &

exec-once = hyprpm reload -n