input {
    kb_layout = ch
    kb_variant = fr
    kb_model = pc105
    kb_options = terminate:ctrl_alt_bksp
    kb_rules =
    numlock_by_default = true

    accel_profile = adaptive
    follow_mouse = 1
    natural_scroll = true

    sensitivity = 0 # -1.0 -1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
    }
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}