animations {
    enabled = true

    bezier = lite, 0.05, 0.9, 0.1, 1.05
    bezier = litein, 0.1, 1.1, 0.1, 1.1
    bezier = liteout, 0.3, -0.3, 0, 1
    bezier = litear, 1, 1, 1, 1

    animation = windows, 1, 6, lite, slide
    animation = windowsIn, 1, 6, litein, slide
    animation = windowsOut, 1, 5, liteout, slide
    animation = windowsMove, 1, 5, lite, slide
    animation = layers, 1, 6, lite, slide top
    animation = border, 1, 1, litear
    animation = borderangle, 1, 30, litear, loop
    animation = fade, 1, 10, lite
    animation = workspaces, 1, 5, lite, slidefade
    animation = workspacesIn, 1, 4, lite, slide
    animation = workspacesOut, 1, 4, lite, slide
}