decoration {
    rounding = 4

    # Change transparency of focused and unfocused windows
    active_opacity = 0.99
    inactive_opacity = 0.9

    shadow {
        ignore_window = false
        range = 6
        color = rgba(181a206c)
    }
}