decoration {
    rounding = 4

    # Change transparency of focused and unfocused windows
    active_opacity = 0.95
    inactive_opacity = 0.80

    shadow {
        ignore_window = false
        range = 4
        color = rgba(2e3440f2)
    }
}