#!/usr/bin/env bash

sudo pacman -Syu --noconfirm
sudo pacman -S --needed --noconfirm base-devel git

if ! command -v paru &>/dev/null; then
    if [ -d storage/paru ]; then
        rm -rf storage/paru
    fi
    git clone https://aur.archlinux.org/paru.git storage/
    cd storage/paru
    makepkg -si
fi

paru -S --noconfirm \
    hyprland \
    hypridle \
    hyprlock \
    hyprpaper \
    hyprpicker \
    waybar \
    grim \
    slurp \
    wlogout \
    wl-clipboard \
    ttf-font-awesome-5 \
    mako \
    blueman \
    gbm \
    hyprland-protocols \
    foot \
    blueman \
    wayland-client \
    wayland-protocols \
    polkit \
    polkit-gnome \
    xdg-desktop-portal \
    xdg-desktop-portal-hyprland \
    wl-clipboard \
    network-manager-applet \
    cliphist \
    solaar \
    tofi \
    thunar \
    foot \
    direnv \
    visual-studio-code-bin \
    greetd \
    greetd-regreet \
    cmake \
    meson \
    cpio \
    cliphist \
    arc-gtk-theme-git \
    papirus-icon-theme \
    waybar \
    pavucontrol \
    noto-fonts \
    noto-fonts-cjk \
    noto-fonts-emoji \
    ttf-roboto
