#!/usr/bin/env bash

sudo pacman -Syu --noconfirm
sudo pacman -S --needed --noconfirm base-devel git

if ! command -v paru &>/dev/null; then
    if [ -d storage/paru ]; then
        rm -rf storage/paru
    fi
    git clone https://aur.archlinux.org/paru.git storage/
    cd storage/paru
    makepkg -si
fi

paru -S --noconfirm \
    hyprland \
    hypridle \
    hyprlock \
    hyprpaper \
    hyprpicker \
    waybar \
    grim \
    slurp \
    wlogout \
    wl-clipboard \
    mako \
    foot \
    blueman \
    xdg-desktop-portal-hyprland \
    wl-clipboard \
    network-manager-applet \
    cliphist \
    solaar \
    tofi \
    greetd \
    greetd-regreet \
    cmake \
    meson \
    cpio \
    cliphist \
    arc-theme \
    papirus-icon-theme \
    waybar \
    pavucontrol
