#!/usr/bin/env bash

./fetcher

configurations=($(ls ./hyprland))

deploy() {
    cp -r "./hyprland/$1" "${HOME}/.config/$1"
    echo "${HOME}/.config/$1 deployed"
}

./uninstall

for configuration in ${configurations[*]}; do
    deploy $configuration
done

sudo cp -r ./greetd /etc/
sudo chown -R greeter:greeter /etc/greetd
echo "greetd deployed"

Hyprland --config installer/hyprland.conf
Hyprland