#!/usr/bin/env bash

configurations=($(ls ./hyprland))

purge() {
    if [ -d "${HOME}/.config/$1" ]; then
        rm -rf "${HOME}/.config/$1"
    fi

    echo "${HOME}/.config/$1 removed"
}

for configuration in ${configurations[*]}; do
    purge $configuration
done

sudo rm -r /etc/greetd
echo "/etc/greetd removed"

sudo systemctl disable --now greetd.service
