bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:272, bringactivetotop
bindm = SUPER, mouse:273, resizewindow

bind = SUPER, M, fullscreen

bind = SUPER SHIFT, right, movewindow, mon:+1
bind = SUPER SHIFT, left, movewindow, mon:-1