general { 
    gaps_in = 5
    gaps_out = 10

    border_size = 4

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = 0xee2C3343
    col.inactive_border = 0xee2B2934

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false 

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc { 
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    vrr = 1
    font_family = "Font Awesome 5 Free" # Set the default font for Hyprland

    enable_anr_dialog = false
}

debug {
    disable_logs = false
    error_position = 1
}