#!/usr/bin/env bash

cd "$(dirname $0)/.."

configurations=($(ls ./configurations))

deploy() {
    cp -r "./configurations/$1" "${HOME}/.config/$1"
    echo "${HOME}/.config/$1 deployed"
}

for configuration in ${configurations[*]}; do
    deploy $configuration
done

sudo localectl set-keymap --no-convert fr_CH

xdg-mime default org.gnome.Nautilus.desktop inode/directory
xdg-mime default org.gnome.Nautilus.desktop x-directory/normal
xdg-mime default org.gnome.Nautilus.desktop x-directory/gnome-default-handler

sudo cp -r ./etc/greetd /etc/

sudo cp -r ./etc/pam.d/greetd /etc/pam.d/greetd

sudo cp ./etc/logid.cfg /etc/logid.cfg

sudo systemctl enable --now firewalld.service
sudo cp -r ./etc/clamav /etc/
sudo cp ./etc/sudoers.d/clamav /etc/sudoers.d/clamav
sudo -u clamav /usr/bin/fangfrisch --conf /etc/fangfrisch/fangfrisch.conf initdb

sudo chown -R greeter:greeter /etc/greetd
echo "greetd deployed"

cp ./vscode/argv.json ${HOME}/.vscode/argv.json
echo "vscode configurated with gnome-keyring"

sudo cp -r ./etc/modules-load.d/ddcci_backlight.conf /etc/modules-load.d/
echo "ddcci_backlight kernel module deployed"

sudo usermod -aG i2c $USER
sudo usermod -aG video $USER

Hyprland --config installer/hyprland.conf

sudo cp -r ./services/* /usr/lib/systemd/system/

touch /run/clamav/clamd.ctl
sudo chown clamav:clamav /run/clamav/clamd.ctl
sudo freshclam
sudo systemctl enable clamav-clamonacc.service
sudo systemctl enable clamav-daemon.service
sudo systemctl enable fangfrisch.timer
sudo systemctl enable --now dnscrypt-proxy.socket

status=$(systemctl is-enabled --user gcr-ssh-agent.socket)
if [ $status != "enabled" ]; then
    systemctl --user enable gcr-ssh-agent.socket --now
fi

status=$(systemctl is-enabled greetd.service)
if [ $status != "enabled" ]; then
    sudo systemctl enable greetd.service --force
fi

status=$(systemctl is-enabled dbus-broker.service)
if [ $status != "enabled" ]; then
    sudo systemctl enable dbus-broker.service
fi

status=$(systemctl is-enabled bluetooth.service)
if [ $status != "enabled" ]; then
    sudo systemctl enable bluetooth.service
fi

status=$(systemctl is-enabled wayland-pipewire-idle-inhibit.service)
if [ $status != "enabled" ]; then
    systemctl --user enable wayland-pipewire-idle-inhibit.service --now
fi

status=$(systemctl is-enabled logid.service)
if [ $status != "enabled" ]; then
    sudo systemctl enable logid.service
fi

read -r -p "Do you want to reboot ? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    reboot
fi
