#!/usr/bin/env bash

basepath="$(dirname $0)/.."
cd $basepath

configurations=($(ls ./configurations))

deploy() {
    cp -r "./configurations/$1" "${HOME}/.config/$1"
    echo "${HOME}/.config/$1 deployed"
}

for configuration in ${configurations[*]}; do
    deploy $configuration
done

sudo cp -r ./etc/greetd /etc/
sudo cp -r ./etc/pam.d/greetd /etc/pam.d/greetd
sudo chown -R greeter:greeter /etc/greetd
echo "greetd deployed"

cp ./vscode/argv.json ${HOME}/.vscode/argv.json
echo "vscode configurated with gnome-keyring"

sudo cp -r ./etc/modules-load.d/ddcci_backlight.conf /etc/modules-load.d/
echo "ddcci_backlight kernel module deployed"

sudo usermod -aG i2c $USER
sudo usermod -aG video $USER

Hyprland --config installer/hyprland.conf

status=$(systemctl is-enabled --user gcr-ssh-agent.socket)
if [ $status != "enabled" ]; then
    systemctl --user enable gcr-ssh-agent.socket --now
fi

status=$(systemctl is-enabled greetd.service)
if [ $status != "enabled" ]; then
    sudo systemctl enable greetd.service --force
fi

status=$(systemctl is-enabled dbus-broker.service)
if [ $status != "enabled" ]; then
    sudo systemctl enable dbus-broker.service --force
fi

status=$(systemctl is-enabled bluetooth.service)
if [ $status != "enabled" ]; then
    sudo systemctl enable bluetooth.service --force
fi

status=$(systemctl is-enabled wayland-pipewire-idle-inhibit.service)
if [ $status != "enabled" ]; then
    systemctl --user enable wayland-pipewire-idle-inhibit.service --now
fi

read -r -p "Do you want to reboot ? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    reboot
fi
