#!/usr/bin/env bash

cd "$(dirname $0)"

. ./package-manager

. ./packages-list

${package_manager} -Sy --sudoloop --noconfirm $packages

read -r -p "Do you want to install amdgpu hardware audio/video decoding ? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    . ./amd-va-packages-list
    ${package_manager} -Sy --sudoloop --noconfirm $amd_va_packages
    echo "Hardware Audio/Video acceleration enabled !"
fi