#!/usr/bin/env bash

./fetcher

basepath="$(dirname $0)/.."
cd $basepath

configurations=($(ls ./hyprland))

deploy() {
    cp -r "./hyprland/$1" "${HOME}/.config/$1"
    echo "${HOME}/.config/$1 deployed"
}

./uninstall

for configuration in ${configurations[*]}; do
    deploy $configuration
done

sudo cp -r ./etc/greetd /etc/
sudo chown -R greeter:greeter /etc/greetd
echo "greetd deployed"

sudo cp -r ./etc/sdboot-manage.conf /etc/
echo "sdboot-manage.conf deployed"

sudo usermod -aG i2c $USER

Hyprland --config installer/hyprland.conf
newgrp

if [$(systemctl is-enabled greetd.service) != "enabled" ]; then
    sudo systemctl enable --now greetd.service --force
fi
