#!/usr/bin/env bash

basepath="$(dirname $0)/.."
cd $basepath

configurations=($(ls ./hyprland))

purge() {
    if [ -d "${HOME}/.config/$1" ]; then
        rm -rf "${HOME}/.config/$1"
        echo "${HOME}/.config/$1 removed"
    fi
}

for configuration in ${configurations[*]}; do
    purge $configuration
done

if [ -d /etc/greetd ]; then
    sudo rm -r /etc/greetd
    echo "/etc/greetd removed"
fi
