#!/usr/bin/env bash

cd "$(dirname ${BASH_SOURCE[0]})"
basedir="$(pwd)"

. ./package-manager

echo "Installing SELinux"

# userspace tools and libraries installation
yes | ${package_manager} --answerclean=All --answerdiff=None --answeredit=None \
    libsepol \
    libselinux \
    checkpolicy \
    secilc \
    setools \
    libsemanage \
    semodule-utils \
    policycoreutils \
    python-ipy \
    selinux-python \
    mcstrans \
    restorecond

echo "Userspace tools and libraries installed"

# pam modules
yes | ${package_manager} --answerclean=All --answerdiff=None --answeredit=None \
    pambase-selinux \
    pam-selinux

echo "Pam modules installed"

# recompile core packages
yes | ${package_manager} --answerclean=All --answerdiff=None --answeredit=None \
    coreutils-selinux \
    findutils-selinux \
    iproute2-selinux \
    logrotate-selinux \
    openssh-selinux \
    psmisc-selinux \
    shadow-selinux \
    cronie-selinux

echo "Core packages rebuilded"

# sudoers
echo "Backing up sudoers"
sudo cp -r /etc/sudoers /etc/sudoers.bak
yes | ${package_manager} --answerclean=All --answerdiff=None --answeredit=None \
    sudo-selinux
echo "Sudo replaced with sudo-selinux"
sudo mv /etc/sudoers.bak /etc/sudoers
echo "Sudoers restored"

# util-linux and systemd
target="systemd-selinux"
cd ${basedir}/../storage
git clone https://aur.archlinux.org/${target}.git
cd ${target}
makepkg
yes | ${package_manager} --answerclean=All --answerdiff=None --answeredit=None \
    systemd-libs-selinux \
    util-linux-selinux
makepkg -si

# post installation
yes | ${package_manager} --answerclean=All --answerdiff=None --answeredit=None \
    dbus-selinux \
    selinux-alpm-hook \
    linux \
    selinux-refpolicy-arch \
    selinux-refpolicy-src \
    setools

# Enabling SELinux LSM
sudo cp -r ${basedir}/../etc/modules-load.d/lsm.conf /etc/modules-load.d/

# maintaining context
sudo systemctl enable restorecond.service