#!/usr/bin/env bash

cd "$(dirname $0)"
basedir="$(pwd)"

. ./package-manager

storage_path="../storage/selinux"

rm -rf ${storage_path}

echo "Installing SELinux"

# userspace tools and libraries installation
${package_manager} --sudoloop -S --noconfirm \
    libsepol \
    libselinux \
    checkpolicy \
    secilc \
    setools \
    libsemanage \
    semodule-utils \
    policycoreutils \
    selinux-python \
    mcstrans \
    restorecond

echo "Userspace tools and libraries installed"

# pam modules
${package_manager} --sudoloop -S --noconfirm \
    pambase-selinux \
    pam-selinux

echo "Pam modules installed"

# recompile core packages
yes | ${package_manager} --sudoloop -S \
    coreutils-selinux \
    findutils-selinux \
    iproute2-selinux \
    logrotate-selinux \
    openssh-selinux \
    pmisc-selinux \
    shadow-selinux \
    cronie-selinux

echo "Core packages rebuilded"

# sudoers
echo "Backing up sudoers"
sudo cp -r /etc/sudoers /etc/sudoers.bak
yes | ${package_manager} --sudoloop -S \
    sudo-selinux
echo "Sudo replaced with sudo-selinux"
sudo mv -r /etc/sudoers.bak /etc/sudoers
echo "Sudoers restored"

# util-linux and systemd
target="systemd-selinux"
cd ${basedir}/../storage
git clone https://aur.archlinux.org/${target}.git
cd ${target}
makepkg
yes | ${package_manager} --sudoloop -S \
    systemd-libs-selinux \
    util-linux-selinux
makepkg -si

# dbus and pacman hook
yes | ${package_manager} --sudoloop -S dbus-selinux
yes | ${package_manager} --sudoloop -S selinux-alpm-hook

# kernel and policy
yes | ${package_manager} --sudoloop -S \
    linux \
    selinux-refpolicy-arch

# Installing references
yes | ${package_manager} --sudoloop -S selinux-refpolicy-src

# SELinux gui
yes | ${package_manager} --sudoloop -S setools

# Enabling SELinux LSM
sudo cp -r ${basedir}/../etc/modules-load.d/lsm.conf /etc/modules-load.d/

# maintaining context
sudo systemctl enable restorecond.service