#!/usr/bin/env bash

cd "$(dirname ${BASH_SOURCE[0]})"
basedir="$(pwd)"
aururl="github.com/archlinuxhardened/selinux"

. ./package-manager

echo "Installing SELinux"

# making sure keys are installed
if [ ! -d "${basedir}/../storage/selinux" ];then
    cd ${basedir}/../storage
    git clone https://github.com/archlinuxhardened/selinux.git
    cd selinux
    ./recv_gpg_keys.sh
fi

repo_dir="${basedir}/../storage/selinux"
install() {
    for package in "$@";do
        cd ${repo_dir}/${package}
        makepkg -si --noconfirm
    done
}

install  \
    libsepol \
    libselinux \
    checkpolicy \
    secilc \
    setools \
    libsemanage \
    semodule-utils \
    policycoreutils \
    python-ipy \
    selinux-python \
    mcstrans \
    restorecond

echo "Userspace tools and libraries installed"

# pam modules
install \
    pambase-selinux \
    pam-selinux
echo "Pam modules installed"

# recompile core packages
install \
    coreutils-selinux \
    findutils-selinux \
    iproute2-selinux \
    logrotate-selinux \
    openssh-selinux \
    psmisc-selinux \
    shadow-selinux \
    cronie-selinux

# sudoers
echo "Backing up sudoers"
sudo cp -r /etc/sudoers /etc/sudoers.bak
install \
    sudo-selinux
echo "Sudo replaced with sudo-selinux"
sudo mv /etc/sudoers.bak /etc/sudoers
echo "Sudoers restored"

# util-linux and systemd
echo "Recompiling systemd"
cd ${repo_dir}/systemd-selinux
makepkg -s
cd ${repo_dir}/systemd-libs-selinux
makepkg -si
cd ${repo_dir}/systemd-selinux
makepkg -si

# post installation
echo "Proceeding to post installation"
install dbus-selinux
install selinux-alpm-hook

yes | ${package_manager} --aururl=${aururl} -Sy --answerclean=None --answerdiff=None --answeredit=None \
    linux \
    selinux-refpolicy-arch \
    selinux-gui

# Enabling SELinux LSM
echo "Making sure SELinux boots at start"
sudo cp -r ${basedir}/../etc/modules-load.d/config-lsm.conf /etc/modules-load.d/
mkinitcpio -p linux

# Maintaining context
echo "Enabling context service"
sudo systemctl enable restorecond