#!/usr/bin/env bash

cd "$(dirname ${BASH_SOURCE[0]})"
basedir="$(pwd)"

. ./package-manager

echo "Installing SELinux"

# userspace tools and libraries installation
${package_manager} -Sy --noconfirm --answerclean=None --answerdiff=None --answeredit=None \
    libsepol \
    libselinux \
    checkpolicy \
    secilc \
    setools \
    libsemanage \
    semodule-utils \
    policycoreutils \
    python-ipy \
    selinux-python \
    mcstrans \
    restorecond

echo "Userspace tools and libraries installed"

# pam modules
${package_manager} -Sy --noconfirm --answerclean=None --answerdiff=None --answeredit=None \
    pambase-selinux \
    pam-selinux
echo "Pam modules installed"

# recompile core packages
echo "Recompiling core-packages"
${package_manager} -Sy --noconfirm --answerclean=None --answerdiff=None --answeredit=None \
    coreutils-selinux \
    findutils-selinux \
    iproute2-selinux \
    logrotate-selinux \
    openssh-selinux \
    psmisc-selinux \
    shadow-selinux \
    cronie-selinux

# sudoers
echo "Backing up sudoers"
sudo cp -r /etc/sudoers /etc/sudoers.bak
${package_manager} -Sy --noconfirm --answerclean=None --answerdiff=None --answeredit=None \
    sudo-selinux
echo "Sudo replaced with sudo-selinux"
sudo mv /etc/sudoers.bak /etc/sudoers
echo "Sudoers restored"

# util-linux and systemd
echo "Recompiling systemd"
${package_manager} -Sy --noconfirm --answerclean=None --answerdiff=None --answeredit=None \
    systemd-selinux

# post installation
echo "Proceeding to post installation"
yes | ${package_manager} -Sy --answerclean=None --answerdiff=None --answeredit=None \
    dbus-selinux \
    selinux-alpm-hook \
    linux \
    selinux-refpolicy-arch \
    selinux-refpolicy-src \
    setools

# Enabling SELinux LSM
echo "Making sure SELinux boots at start"
sudo cp -r ${basedir}/../etc/modules-load.d/config-lsm.conf /etc/modules-load.d/
sudo cp -r ${basedir}/../etc/modprobe.d/lsm.conf /etc/modprobe.d/

# Maintaining context
echo "Enabling context service"
sudo systemctl enable restorecond