#!/usr/bin/env bash

configurations=($(ls ./hyprland))

purge() {
    if [ -d "${HOME}/.config/$1" ]; then
        rm -rf "${HOME}/.config/$1"
        echo "${HOME}/.config/$1 removed"
    fi
}

for configuration in ${configurations[*]}; do
    purge $configuration
done

if [ -d /etc/greetd ]; then
    sudo rm -r /etc/greetd
    echo "/etc/greetd removed"
fi

if [ -d /etc/sdboot-manage.conf ]; then
    sudo rm -r /etc/sdboot-manage.conf
    echo "/etc/sdboot-manage.conf removed"
fi

read -r -p "Do you want to clean packages ? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    ./cleaner
fi
