#!/usr/bin/env bash

basepath="$(dirname $0)"
cd $basepath

./revert

read -r -p "Do you want to clean packages ? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    ./cleaner
fi
