source = sources/input.conf

source = sources/variables/variables.conf

source = sources/rules.conf

source = sources/plugins.conf

source = sources/monitors.conf

source = sources/executables.conf

source = sources/keybindings/keybindings.conf